spring.application.name=SwiftCheckout

spring.datasource.url=jdbc:mysql://localhost:3306/swiftcheckout
spring.datasource.username=root
spring.datasource.password=Hari@9655

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081

spring.security.user.name=HARI
spring.security.user.password=12345